# Setup
title:        Auditing Black Box Models
tagline:      A hands-on tutorial at FAT* 2018.
baseurl:      "https://algofairness.github.io/fatconference-2018-auditing-tutorial/"
paginate:     1
locale:       "en"
exclude:      [ "README.md", "Gemfile.lock", "Gemfile", "jekyll-cayman-theme.gemspec" ]

# About/contact
author:
  name:       Carlos Scheidegger, Suresh Venkatasubramanian, Charlie Marx
  url:        https://algofairness.github.io/fatconference-2018-auditing-tutorial/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

theme: jekyll-theme-cayman
